#!/bin/bash 

# 8/5/2013  changes with new ubuntu - compiled ffmpeg instead of binary
#			changed to sox instead of mplayer.
# 4/13/2013 New method of using ffmpeg to compress video
# 4/12/2013 Made mjpegtools deafult, changed file name method
# 4/9/2013  Added function to work without mjpegtools.
# 4/7/2013  Michael Cassera

# A BASH script to compress and combine GoPro video files for Time Lapse
#
# Default values are:		Date is new directory
#							Final File is Date+Rate.mp4
#							Rate is 24x normal speed
#							The Video is NOT uploaded to YouTube
#	
# Usage    timex [options]	
#
# Tools needed to run this script:	ffmpeg
#									sox
#									mjpegtools [optional]
#									youtube-upload [optional]
#

#Default Values
ytUser=username					# YouTube Username
ytPass=password					# YouTube Password
read dt <<< "`date -I`"			# Get date in -I format for File Name
rate="24"						# Video/Audio multiplier
YT=0							# upload to YouTube	(no)
Sound=0							# Compress sound default (no)
mjpeg=0							# Use mjpegtools (no)

# Functions to do the heavy lifting.  File is passed as ${1} to ffmpeg.
# Fuction Rip video from file and compress
function vidCompress()			# Use ffmpeg & mjpegtools to compress Video (Faster, better)
{		
	echo "   Ripping video & compressing." >>timex.log
	ffmpeg -i ${1} -f yuv4mpegpipe - | yuvfps -s $fps:1 -r 30:1  | ffmpeg -f yuv4mpegpipe -i - -b:v 16384k -y fast.mp4
}

function videoRipCompress()		# Use ffmpeg to compress Video (Slower Less Quality)
{
	mkdir tmp					# Make temp directory to store frames
	echo "   Ripping video to frames in tmp." >>timex.log
	ffmpeg -i ${1} -f image2 tmp/frame%7d.jpg	# extract frames from video

# Count frames and delete unused frames
	n="0"
	echo "Removing extra frames..."
	while read line					
	do
		n=$[$n+1]
		keep=$[$n%$rate]		# is the remainder of frame/rate = 0
		if [ $keep = "0" ]
		then
			echo -n "."		# Keep the frame divisible by rate
		else
			rm -f $line		# Delete frames in between
		fi
	done <<< "`ls -1dtr tmp/*.jpg`"		# get all *.jpg files in mod order from tmp dir
	
# Now renumber frames to be used by ffmpeg	
	n="0"
	while read line			
	do
		n=$[$n+1]
		nm="frame"
		if [ $n -lt "10" ]	 	# add a "0" if less than 10
		then
		nm=$nm"0"
		fi
		if [ $n -lt "100" ]		# add a "0" if less than 100
		then
			nm=$nm"0"	
		fi
		if [ $n -lt "1000" ]	# add a "0" if less than 1000
		then
			nm=$nm"0"
		fi
		if [ $n -lt "10000" ]	# add a "0" if less than 10000
		then
			nm=$nm"0"
		fi
		if [ $n -lt "100000" ]	# add a "0" if less than 100000
		then
			nm=$nm"0"
		fi
		if [ $n -lt "1000000" ]	# add a "0" if less than 1000000
		then
			nm=$nm"0"
		fi
		nm=$nm$n".jpg"			# add the number i + .jpg suffix to the filename
		mv -v $line tmp/$nm			# rename the old file to the new file
	done <<< "`ls -1dtr tmp/*.jpg`"		# get all *.jpg files in mod order from tmp dir

	echo "   Rebuilding mp4 from frames." >>timex.log
	ffmpeg -f image2 -r 30 -i tmp/frame%7d.jpg -b:v 16384k -y fast.mp4
	echo "   Clearing tmp directory." >>timex.log
	rm -rfv tmp
}

# Function Rip audio from file and compress
function audioCompress()
{
	echo "   Ripping audio & compressing." >>timex.log
	ffmpeg -i ${1} -vn -ac 2 -ar 44100 -ab 128k -f wav sound.wav
	sox sound.wav output.wav speed $rate
	#mplayer -af scaletempo -speed $rate sound.wav -vc null -vo null -ao pcm:fast:waveheader:file=output.wav
	rm -fv sound.wav
}

# Function Attach compressed audio to compressed viedo
function audio2video()
{
	echo "   Re-attaching audio to video." >>timex.log
	fnme="fastA"${1}".mp4"
	ffmpeg -i fast.mp4 -i output.wav $fnme
	rm -fv output.wav
	rm -fv fast.mp4
}

# Function rerender to mpeg to append to working file
function render2mpg()
{
	echo "   Rendering to mpeg." >>timex.log
	ffmpeg -i fastA.mp4 -b:v 16384k temp.mpg
	rm -fv fastA.mp4
}

# Function Append new compressed file to working file
function add2work()
{
	echo "   Adding to work.mpg." >>timex.log
	cat work.mpg temp.mpg > temp2.mpg
	rm -fv work.mpg
	rm -fv temp.mpg
	mv temp2.mpg work.mpg
}

# Function for usage
function usage {
	echo
	echo "Usage: timex [options] "
	echo 
	echo "  Options"
	echo "	-r[rate] Rate to speed up video, default is 24"
	echo "	-m       Use mjpeg tools to compress video (mjpegtools required)"
	echo "	-a       Compress audio (mplayer required)"
	echo "	-y       Upload to Youtube (youtube-upload required)"
	echo "	           Program will ask for name, description, user and password"
	echo " 	-o       output filename"
	echo "	-h       This help message"
	echo
	echo "	Tools needed to run this script:"	
	echo "			ffmpeg	(Video I/O)"
	echo "			mjpegtools  [recommended](Video Compression)"
	echo "			sox	 [optional](Audio Compression)"
	echo "			youtube-upload  [optional](Command Line upload to Youtube)"
	echo 
}


#  Program Starts here.
#  Check parameters
while getopts r:mayho: option
do
	case $option in
	r)
		rate=$OPTARG	# rate multiplyer
		;;
	m)
		mjpeg=1		# use mjpegtools
		;;		
	a)
		Sound=1 	# compress sound
		;;			
	y)
		YT=1		#upload to Youtube
		;;		
	h)
		usage		# help message
		exit 0;;	
	o)
		fn=$OPTARG	# output filename
		;;
	*)				# Any other option is an error
		usage
		exit 1;;		
	esac
done


#  Start Log File
echo "timex log file" > timex.log
echo >>timex.log
 

#  Run a directory listing and store in an array.  The listing is sorted by modified date.
echo "File List:" >>timex.log
echo "File List:"
while read line
do
	fname=("${fname[@]}" $line)
	echo $line >>timex.log
	echo $line
done <<< "`ls -1dtr *.MP4`"
echo
echo >>timex.log	

#  Calculate rate for ffmpeg 
fps=$[$rate*30]
echo "Rate is "$rate"X, "$fps" frame/sec."
echo "Rate is "$rate"X, "$fps" frame/sec." >>timex.log
echo

#  Get Youtube info if uploading to Youtube
if [ $YT = "1" ]
then
	echo -n 'Enter the title of the Video>  '
	read YTTitle					#The Title
	echo -n 'Enter a short description of the Video> '
	read YTDescription				#The Description
	echo 'Select a Category for your Video:'
	echo
	echo '   a) Autos & Vehicals'
	echo '   b) Comedy'
	echo '   c) Education'
	echo '   d) Film & Animation'
	echo '   e) Gaming'
	echo '   f) Howto & Style'
	echo '   g) Music'
	echo '   h) News & Politics'
	echo '   i) Nonprofits & Activism'
	echo '   j) People & Blogs'
	echo '   k) Pets & Animals'
	echo '   l) Science & Technology'
	echo '   m) Sports'
	echo '   n) Travel & Events'
	echo
	echo -n 'default is {m} Sports> '
	read catChoose
	YTCat="Sports"
	if [ $catChoose = "a" ]
	then
		YTCat="Autos & Vehicals"
	fi
	if [ $catChoose = "b" ]
	then
		YTCat="Comedy"
	fi
	if [ $catChoose = "c" ]
	then
		YTCat="Education"
	fi
	if [ $catChoose = "d" ]
	then
		YTCat="Film & Animation"
	fi
	if [ $catChoose = "e" ]
	then
		YTCat="Gaming"
	fi
	if [ $catChoose = "f" ]
	then
		YTCat="Howto & Style"
	fi
	if [ $catChoose = "g" ]
	then
		YTCat="Music"
	fi
	if [ $catChoose = "h" ]
	then
		YTCat="News & Politics"
	fi
	if [ $catChoose = "i" ]
	then
		YTCat="Nonprofits & Activism"
	fi
	if [ $catChoose = "j" ]
	then
		YTCat="People & Blogs"
	fi
	if [ $catChoose = "k" ]
	then
		YTCat="Pets & Animals"
	fi
	if [ $catChoose = "l" ]
	then
		YTCat="Science & Technology"
	fi
	if [ $catChoose = "m" ]
	then
		YTCat="Sports"
	fi
	if [ $catChoose = "n" ]
	then
		YTCat="Travel & Events"
	fi
	echo $YTCat" selected."
	echo "Will upload to YouTube with the title: "$YTTitle >>timex.log
	echo >>timex.log
	echo -n 'Enter YouTube username> '
	read ytUser
	echo -n 'Enter YouTube password> '
	read -s ytPass
else
	echo "Not uploading to YouTube" >>timex.log
	echo >>timex.log
fi


#  Create name of final video name
if [ -z "$fn" ];					# if no filename was given
then
	fn=$dt-$rate.mp4				# set to default name
fi				
echo "Final Video name is: "$fn >>timex.log
echo >>timex.log


#  Run a loop to pass file names to time lapse function	
i="0"								# The Counter
x=${#fname[@]}						# Number of elements in the array
while [ $i -lt $x ]
do
	date >>timex.log				# Time Stamp log file
	echo " Working on "${fname[$i]}"." >>timex.log
	if [ $mjpeg = "1" ]				# Compress Video
	then
		vidCompress ${fname[$i]}	# Used mjpeg tools	
	else
		videoRipCompress ${fname[$i]}	# Use ffmpeg
	fi
	if [ $Sound = "1" ]
	then
		audioCompress ${fname[$i]}	# rip & compress Audio
		audio2video	$[$i]				# combine audio to video
	else
		mv fast.mp4 fastA$[$i].mp4		# skip audio compression, just rename
	fi
	#render2mpg						# render to mpg
	#add2work						# append to work.mpg
	i=$[$i+1]						# next file
	echo >>timex.log
done	


#  Finish up by concatenate files with date & rate in name. Remove work file.	
date >>timex.log
echo "   Joining all files together" >>timex.log
echo >>timex.log
#  Put the files together using concat
while read line					
	do
		echo "file '"$line"'" >>filelist.txt
	done <<< "`ls -1dtr fastA*.mp4`"		# get all fastAx.mp4 files
ffmpeg -f concat -i filelist.txt -c copy $fn
# remove all work files
while read line					
	do
		rm -fv $line
	done <<< "`ls -1dtr fastA*.mp4`"		# get all fastAx.mp4 files
rm -fv filelist.txt


#  Upload to YouTube if YT = 1
if [ $YT = "1" ] 
then
	date >>timex.log
	echo "   Uploading "$YTTitle" to YouTube" >>timex.log
	echo >>timex.log
	youtube-upload --email $ytUser --password=$ytPass --title="$YTTitle" --description="$YTDescription" --category="$YTCat" $fn 
fi

#  We are done!
date >>timex.log
echo "   Done!" >>timex.log


